# Generated by Django 5.2.12 on 2026-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(),
        ),
    ]
