# Generated by Django 5.2.12 on 2026-04-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_logentry_student_phone_assignment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('Class 11', 'Class 11'), ('Class 12', 'Class 12'), ('UG-1', 'UG Year 1'), ('UG-2', 'UG Year 2'), ('UG-3', 'UG Year 3'), ('PG-1', 'PG Year 1'), ('PG-2', 'PG Year 2')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('ID', 'ID Proof'), ('FORM', 'Admission Form'), ('MEDICAL', 'Medical Record'), ('CERTIFICATE', 'Certificate'), ('FEE', 'Fee Receipt'), ('ASSIGNMENT', 'Assignment'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='drive_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
