# Generated by Django 5.2.12 on 2026-04-14 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_document_document_file_student_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('Administration', 'Administration'), ('Accounts', 'Accounts'), ('Library', 'Library'), ('Security', 'Security'), ('Housekeeping', 'Housekeeping'), ('IT Support', 'IT Support'), ('Transport', 'Transport'), ('Medical', 'Medical'), ('Sports', 'Sports'), ('Canteen', 'Canteen'), ('Other', 'Other')], default='Administration', max_length=50)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part-time', 'Part-Time'), ('temporary', 'Temporary')], default='permanent', max_length=20)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('classes_taught', models.CharField(blank=True, help_text='Comma-separated class names', max_length=500, null=True)),
                ('qualification', models.CharField(choices=[('B.Ed', 'B.Ed'), ('M.Ed', 'M.Ed'), ('PhD', 'PhD'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('B.A', 'B.A'), ('M.A', 'M.A'), ('Other', 'Other')], default='B.Ed', max_length=20)),
                ('experience_yrs', models.IntegerField(default=0, help_text='Years of experience')),
                ('specialization', models.CharField(blank=True, max_length=300, null=True)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('visiting', 'Visiting'), ('probation', 'Probation')], default='permanent', max_length=20)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('principal', 'Principal')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
