# Generated by Django 5.2.12 on 2026-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_assignment_created_at_assignment_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_submissions/'),
        ),
    ]
